### ISSUE TITLE
AttributeError: 'GDEncoder_stu' object has no attribute 'iafsqueeze'

### ISSUE THREAD

**Issue by yachour1** [Petrichor625/HLTP#6]
https://github.com/Petrichor625/HLTP/blob/ebd72e219a6b08990284d10849385bcc1699a866/trajectory_visualization.py#L120C54-L120C70

**Description:**
I encountered an error while trying to run the script trajectory_visualization.py. The script attempts to access an attribute 'iafsqueeze.v_mem' from the GDEncoder_stu object, but it seems that this attribute doesn't exist in the model. Here are the details of the error:

**Error Traceback:**
  File "trajectory_visualization.py", line 120, in <module>
    gdEncoder.iafsqueeze.v_mem = state_dict.get('iafsqueeze.v_mem', None)
  File "/root/anaconda3/envs/Behavior_aware/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'GDEncoder_stu' object has no attribute 'iafsqueeze'

**What I Tried:**

I tried manually inspecting the model class GDEncoder_stu but couldn't find the iafsqueeze attribute.
Checked if state_dict contained iafsqueeze.v_mem, but it seems that it is not part of the model.

**Comment by FranklinNotOld** [comment]
Sorry about that. It seems that I mixed up the visualization code from another projetct. I will upgrade it several days later. If you are urgent about the visualization code, you can look through STDAN project first.

**Comment by Petrichor625** [comment]
Hello,

Thank you for bringing this up and for the details you provided—it’s very helpful.

I wanted to let you know that we’ve recently uploaded a fully updated version of the repository, including all necessary model parameters and weight files. This update addresses previous compatibility issues, and the new version should resolve the error you encountered with the codes.

Please pull the latest version and try running the updated script. If you encounter any other issues or have further questions, feel free to reach out. We appreciate your patience and support as we worked to improve the repository.

Thank you again for your understanding, and happy experimenting!
